### ISSUE TITLE
error cant find ".names" file

### ISSUE THREAD

**Issue by lidorshimoni** [BMW-InnovationLab/BMW-YOLOv4-Inference-API-GPU#7]
I get the following error when trying to load the models from the docs web interface.
the obj.name file is in the "models" dir and I tried to put relate and absolute path in the Yolo.data file.

`names=/home/sim/Desktop/BMW-YOLOv4-Inference-API-GPU/models/tiny_fhd/obj.names
`

```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:1234 (Press CTRL+C to quit)
Couldn't open file: /home/sim/Desktop/BMW-YOLOv4-Inference-API-GPU/models/tiny_fhd/obj.names
```

**Comment by hadikoub** [comment]
As you are using the inference api inside a docker container the path should be like in this example 
`names=/models/<model_name>/obj.names`

**Comment by lidorshimoni** [comment]
thanks it solved my issue!
