### ISSUE TITLE
where is the predict_batch option?

### ISSUE THREAD

**Issue by lidorshimoni** [BMW-InnovationLab/BMW-YOLOv4-Inference-API-GPU#8]
there's no "predict_batch" option in the web interface...

> models/{model_name}/predict_batch (POST)
> Performs inference on specified model and a list of images, and returns bounding boxes

**Comment by hadikoub** [comment]
The predict_batch is not visible on the swagger interface but a request can be sent to that endpoint using requests in python or any other suitable method (curl, etc..)

The input for this endpoint are: 
model_name :str and 
input_data : List[UploadFile]

**Comment by lidorshimoni** [comment]
in what format the list of images should be? can you be more specific?
and if I want to run inference on the entire batch, something like 100 pictures, in order to compare the performance of two trained nets (two weight files). is this the right tool to compare performance?

**Comment by hadikoub** [comment]
The format should be `UploadFile` please refer to official fastapi doc. https://fastapi.tiangolo.com/tutorial/request-files/
If you want to compare 2 models you can use this method or if you run into trouble you can write a script that send a request to /detect or /predict_image endpoint for each image and then compare the output of both.
